### PR TITLE
Added simple CLI

### PR DESCRIPTION
**Pull request by tianer2820**
Added a simple command line interface so this can be called from other programs

### CODE REVIEW

**Comment by charlotte-xiao** [comment]
Can we write this CLI function in Service to handle it? Not just write the CLI logic in the `main` function. You may need to refactor it.

**Comment by charlotte-xiao** [comment]
But your idea is good~ 👍

**Comment by tianer2820** [comment]
Sorry I'm not very familiar with java, what do you mean by Service?

**Comment by charlotte-xiao** [comment]
> Sorry I'm not very familiar with java, what do you mean by Service?

Yes, maybe we can temporarily use the service to handle CLI logic. Just keeping class code has simple responsibility.

**Pull request merged**
